# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lr', '0002_remove_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default=1978),
            preserve_default=False,
        ),
    ]
